#!/usr/bin/env node
/**
 * extract-icons.js — Maintainer build script.
 *
 * Extracts SVG markup data from react-icons npm packages into a single
 * `icons.js` file that can be used at runtime WITHOUT react/react-dom/react-icons.
 *
 * Prerequisites:
 *   npm install react react-dom react-icons   (in a temp dir)
 *
 * Usage:
 *   node scripts/extract-icons.js [--icons-dir <path-to-react-icons>] [--output <path>]
 *
 * Default: looks for react-icons in ./node_modules/react-icons, outputs to ./scripts/icons.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Libraries to extract (must match KEEP_LIBS in bundle-deps.sh / html2pptx.md)
const LIBRARIES = ['fa6', 'md', 'lu', 'ai', 'io5'];

function extractIcons(iconsBasePath) {
  const result = {};
  let totalCount = 0;
  const React = require('react');
  const ReactDOMServer = require('react-dom/server');

  const extractSvgData = (svgString) => {
    const openMatch = svgString.match(/^<svg\b([^>]*)>/);
    if (!openMatch) return null;

    // Runtime supplies width/height and xmlns. Keep drawing attributes such as
    // viewBox, fill, stroke, stroke-width, linecap, linejoin, etc.
    const attrs = openMatch[1]
      .replace(/\s(width|height|xmlns)="[^"]*"/g, '')
      .trim();
    const body = svgString
      .replace(/^<svg\b[^>]*>/, '')
      .replace(/<\/svg>$/, '')
      .replace(/><\/(path|circle|rect|line|polyline|polygon|ellipse)>/g, '/>');

    if (!attrs || !/\bviewBox=/.test(attrs) || !body) return null;
    return { attrs, body };
  };

  for (const lib of LIBRARIES) {
    const libPath = path.join(iconsBasePath, lib);
    if (!fs.existsSync(libPath)) {
      console.error(`WARNING: ${libPath} not found, skipping`);
      continue;
    }

    // react-icons exports all icons from the index file
    let mod;
    try {
      mod = require(path.resolve(libPath));
    } catch (e) {
      console.error(`ERROR loading ${lib}: ${e.message}`);
      continue;
    }

    let libCount = 0;

    for (const [name, Component] of Object.entries(mod)) {
      if (typeof Component !== 'function') continue;
      // Skip non-icon exports (like GenIcon, IconContext, etc.)
      if (name === 'GenIcon' || name === 'IconContext' || name === 'IconBase') continue;

      try {
        // Render to SVG string
        const svgString = ReactDOMServer.renderToStaticMarkup(
          React.createElement(Component, { size: '24' })
        );

        const svgData = extractSvgData(svgString);
        if (!svgData) continue;

        result[name] = svgData;
        libCount++;
      } catch (e) {
        // Skip icons that fail to render
        continue;
      }
    }

    console.log(`  ${lib}: ${libCount} icons extracted`);
    totalCount += libCount;
  }

  return { icons: result, count: totalCount };
}

function main() {
  const args = process.argv.slice(2);
  let iconsDir = path.join(process.cwd(), 'node_modules', 'react-icons');
  let outputPath = path.join(__dirname, 'icons.js');

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--icons-dir' && args[i + 1]) {
      iconsDir = path.resolve(args[++i]);
    } else if (args[i] === '--output' && args[i + 1]) {
      outputPath = path.resolve(args[++i]);
    }
  }

  if (!fs.existsSync(iconsDir)) {
    console.error(`ERROR: react-icons not found at ${iconsDir}`);
    console.error('Install first: npm install react react-dom react-icons');
    process.exit(1);
  }

  console.log(`[extract-icons] extracting from ${iconsDir}`);
  console.log(`[extract-icons] libraries: ${LIBRARIES.join(', ')}`);

  const { icons, count } = extractIcons(iconsDir);

  // Generate the output module
  const header = `// Auto-generated by extract-icons.js — DO NOT EDIT\n` +
    `// ${count} icons from: ${LIBRARIES.join(', ')}\n` +
    `// Generated: ${new Date().toISOString()}\n` +
    `'use strict';\n\n`;

  const content = header + `module.exports = ${JSON.stringify(icons)};\n`;

  fs.writeFileSync(outputPath, content);
  const sizeKB = (Buffer.byteLength(content) / 1024).toFixed(0);
  console.log(`[extract-icons] wrote ${outputPath} (${count} icons, ${sizeKB}KB)`);
}

main();
